# Generated by Django 5.0.1 on 2024-01-15 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Hodim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to='media')),
                ('tele', models.CharField(max_length=40)),
                ('face', models.CharField(max_length=40)),
                ('inst', models.CharField(max_length=40)),
                ('twitter', models.CharField(max_length=40)),
                ('data', models.DateField(auto_now=True)),
                ('lavozim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfiles.title')),
            ],
        ),
    ]
