# Generated by Django 5.0.1 on 2024-01-18 14:15

import myfiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0002_lavozim_alter_hodim_lavozim'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media')),
                ('Name', models.CharField(max_length=15)),
                ('Turi', models.CharField(max_length=20, verbose_name=myfiles.models.Turi)),
                ('Category', models.CharField(max_length=30)),
                ('data', models.DateField()),
                ('Klent', models.CharField(max_length=30)),
                ('Link', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Servis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(upload_to='media')),
                ('nomi', models.CharField(max_length=15)),
                ('malumot', models.TextField()),
                ('Sana', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Turi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turi', models.CharField(max_length=25)),
            ],
        ),
    ]
