# Generated by Django 5.0.1 on 2024-01-18 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0003_portfolio_servis_turi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='Turi',
            new_name='Turlari',
        ),
    ]
